:asset_root: public
:load_path:
  - app/javascripts
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
  - vendor/plugins/*/app/javascripts
:builds:
  :default:
    - app/javascripts/application.js
    - app/javascripts/**/*.js
